// adb install package of an app mod: the mod built onto the stock APK, re-signed with the
// project key, the pinned platform-tools adb for macOS/Linux/Windows and scripts the user runs.
// HyperKitchen never runs adb.
//
// adb commands used (adb help, platform-tools 37.0.1): wait-for-device, get-state,
// shell getprop, install -r (replace existing application), -s SERIAL via the script args.

import { existsSync } from 'node:fs'
import { chmod, mkdir, rm, writeFile } from 'node:fs/promises'
import { basename, join } from 'node:path'
import { cloneOrCopy } from '../fsutil'

const q = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`

const ADB_PAYLOADS: Array<[string, string, boolean]> = [
  ['platform-tools/macos/adb', 'bin/macos/adb', true],
  ['platform-tools/linux/adb', 'bin/linux/adb', true],
  ['platform-tools/windows/adb.exe', 'bin/windows/adb.exe', false],
  ['platform-tools/windows/AdbWinApi.dll', 'bin/windows/AdbWinApi.dll', false],
  ['platform-tools/windows/AdbWinUsbApi.dll', 'bin/windows/AdbWinUsbApi.dll', false],
  ['platform-tools/NOTICE.txt', 'bin/NOTICE-platform-tools.txt', false]
]

export interface AdbScriptOpts {
  device: string | null
  packageName: string
  apk: string
  generator: string
}

function incompatibleHelp(pkg: string): string[] {
  return [
    `The device already has ${pkg} signed with a different key.`,
    'If it is part of the ROM (a system app), adb cannot replace it: add the mod to the recipe,',
    'build the ROM and flash it instead.',
    'If it is a removable app, uninstall it first (this DELETES its data), then run this again:',
    `  adb uninstall ${pkg}`
  ]
}

export function renderAdbScript(o: AdbScriptOpts & { os: 'macos' | 'linux' }): string {
  const l: string[] = []
  const say = (s: string): void => {
    l.push(`echo ${q(s)}`)
  }
  const bundled = `bin/${o.os}/adb`
  l.push('#!/bin/sh')
  l.push(`# Generated by ${o.generator}. HyperKitchen never runs this script; you do.`)
  l.push('# Needs USB debugging on. Usage: ./script.sh [adb options, e.g. -s SERIAL]')
  l.push('# Set ADB=/path/to/adb to use a specific binary.')
  l.push('set -u')
  l.push('cd "$(dirname "$0")" || exit 1')
  l.push('ADB="${ADB:-}"')
  l.push('if [ -z "$ADB" ]; then')
  l.push(
    `  if [ -f ${q(bundled)} ]; then ADB=${q(bundled)}; chmod +x "$ADB" 2>/dev/null; else ADB=adb; fi`
  )
  if (o.os === 'macos') {
    // A browser download quarantines the bundled binary; clear it on this one file.
    l.push(`  [ "$ADB" = ${q(bundled)} ] && xattr -d com.apple.quarantine "$ADB" 2>/dev/null`)
  }
  l.push('fi')
  l.push('OPTS="$*"')
  l.push('die() { echo "ERROR: $*" >&2; exit 1; }')
  l.push('command -v "$ADB" >/dev/null 2>&1 || die "adb not found (set ADB=...)"')
  l.push('echo "Waiting for the device (USB debugging on, this computer allowed)..."')
  l.push('$ADB $OPTS wait-for-device || die "no device"')
  l.push('state=$($ADB $OPTS get-state 2>/dev/null)')
  l.push('[ "$state" = "device" ] || die "the device is $state, not ready for adb"')
  if (o.device) {
    l.push(`dev=$($ADB $OPTS shell getprop ro.product.device | tr -d '\\r')`)
    l.push(
      `[ "$dev" = ${q(o.device)} ] || die "this APK is for ${o.device}, the device says '$dev'"`
    )
  }
  say(`This installs ${o.packageName} signed with the HyperKitchen project key.`)
  say('It is not Xiaomi-signed: it cannot update the copy in the ROM, and it gets no store or')
  say('OTA updates. Later mods of this app from the same project install over it.')
  l.push('printf "Type yes to continue: "')
  l.push('read -r answer')
  l.push('[ "$answer" = "yes" ] || die "aborted"')
  l.push(`out=$($ADB $OPTS install -r ${q(o.apk)} 2>&1)`)
  l.push('echo "$out"')
  l.push('case "$out" in')
  l.push('  *Success*) echo "Done." ;;')
  l.push('  *UPDATE_INCOMPATIBLE*|*INCONSISTENT_CERTIFICATES*|*SHARED_USER_INCOMPATIBLE*)')
  for (const s of incompatibleHelp(o.packageName)) l.push(`    echo ${q(s)} >&2`)
  l.push('    exit 1 ;;')
  l.push('  *) die "adb install failed" ;;')
  l.push('esac')
  return l.join('\n') + '\n'
}

export function renderAdbBatch(o: AdbScriptOpts): string {
  const l: string[] = []
  const fail = (msg: string): string => `echo ERROR: ${msg} & pause & exit /B 1`
  l.push('@echo off')
  l.push(`rem Generated by ${o.generator}. HyperKitchen never runs this script; you do.`)
  l.push('rem Needs USB debugging on.')
  l.push('setlocal EnableDelayedExpansion')
  l.push('cd /d "%~dp0"')
  l.push('set adb=bin\\windows\\adb.exe')
  l.push(`if not exist %adb% ${fail('%adb% not found.')}`)
  l.push('echo Waiting for the device (USB debugging on, this computer allowed)...')
  l.push(`%adb% wait-for-device || (${fail('no device')})`)
  if (o.device) {
    l.push('set dev=')
    l.push("for /f %%A in ('%adb% shell getprop ro.product.device') do set dev=%%A")
    l.push(
      `if not "!dev!"=="${o.device}" ${fail(`this APK is for ${o.device}, the device says !dev!`)}`
    )
  }
  l.push(`echo This installs ${o.packageName} signed with the HyperKitchen project key.`)
  l.push(
    'echo It is not Xiaomi-signed: it cannot update the copy in the ROM, and it gets no store or'
  )
  l.push('echo OTA updates. Later mods of this app from the same project install over it.')
  l.push('set /p answer=Type yes to continue: ')
  l.push('if /i not "!answer!"=="yes" exit /B 1')
  l.push(`%adb% install -r "${o.apk}" > "%TEMP%\\hk-adb-install.txt" 2>&1`)
  l.push('type "%TEMP%\\hk-adb-install.txt"')
  l.push('findstr /c:"Success" "%TEMP%\\hk-adb-install.txt" >nul && (echo Done. & exit /B 0)')
  l.push(
    'findstr /c:"UPDATE_INCOMPATIBLE" /c:"INCONSISTENT_CERTIFICATES" /c:"SHARED_USER_INCOMPATIBLE" "%TEMP%\\hk-adb-install.txt" >nul && ('
  )
  for (const s of incompatibleHelp(o.packageName))
    l.push(`  echo ${s.replace(/[()&|<>^]/g, '^$&')}`)
  l.push('  pause & exit /B 1')
  l.push(')')
  l.push(fail('adb install failed'))
  return l.join('\r\n') + '\r\n'
}

/** Write bin/, the scripts and README next to an already signed APK in `dir`. */
export async function writeAdbPackage(opts: {
  dir: string
  apkName: string
  commonBinDir: string
  device: string | null
  packageName: string
  target: string
  certSha256: string
  generator: string
}): Promise<{ scripts: string[]; bundledAdb: boolean }> {
  let bundledAdb = true
  for (const [src, dst, exec] of ADB_PAYLOADS) {
    const from = join(opts.commonBinDir, src)
    if (!existsSync(from)) {
      bundledAdb = false
      continue
    }
    await mkdir(join(opts.dir, dst, '..'), { recursive: true })
    await rm(join(opts.dir, dst), { force: true })
    await cloneOrCopy(from, join(opts.dir, dst))
    if (exec) await chmod(join(opts.dir, dst), 0o755)
  }
  const base: AdbScriptOpts = {
    device: opts.device,
    packageName: opts.packageName,
    apk: opts.apkName,
    generator: opts.generator
  }
  const scripts: string[] = []
  for (const os of ['macos', 'linux'] as const) {
    const name = `${os}_adb_install.sh`
    await writeFile(join(opts.dir, name), renderAdbScript({ ...base, os }), { mode: 0o755 })
    scripts.push(name)
  }
  await writeFile(join(opts.dir, 'windows_adb_install.bat'), renderAdbBatch(base))
  scripts.push('windows_adb_install.bat')
  // data-app APKs are copied to /data on first boot and stay removable; the rest are system apps.
  const systemApp = !opts.target.includes('/data-app/')
  await writeFile(
    join(opts.dir, 'README.txt'),
    [
      `${opts.apkName}: ${opts.packageName} (${basename(opts.target)}) with the edits of this mod,`,
      `re-signed with the HyperKitchen project key (certificate SHA-256 ${opts.certSha256}).`,
      '',
      'Run the script for your computer with the phone connected and USB debugging on.',
      'HyperKitchen never runs adb; you do.',
      '',
      'Signature: this APK is NOT signed by Xiaomi. It can only replace a copy signed with',
      'the same project key, and it gets no updates from the store or OTA.',
      systemApp
        ? `${opts.target} is a system app in the ROM: while the phone still has the Xiaomi-signed copy, adb install fails (INSTALL_FAILED_UPDATE_INCOMPATIBLE). Use the recipe and a ROM build for it, or remove it from the ROM first (debloat).`
        : `${opts.target} is installed as a removable app: uninstall the Xiaomi-signed copy first (adb uninstall ${opts.packageName}; this deletes its data).`,
      '',
      'The project key is in <project>/keys/. Keep it: without it, later builds of this mod',
      'cannot be installed over this one.',
      bundledAdb
        ? 'bin/ holds Google platform-tools adb 37.0.1 (see bin/NOTICE-platform-tools.txt).'
        : '',
      ''
    ].join('\n')
  )
  return { scripts, bundledAdb }
}
