// Flash scripts for the fastboot package. HyperKitchen never runs them; the user does.
//
// The partition list and order come from the stock Xiaomi scripts (flash_all.sh keeps the
// "wipe data" steps, flash_all_except_storage.sh does not). What is dropped and why:
//   - the crclist / sparsecrclist block: sparsecrclist holds CRCs of the stock super.img
//     chunks, so a device with CRC checking on would reject a rebuilt super;
//   - getvar checks written with `grep -oP`, which BSD grep on macOS does not support;
//     they are replaced with portable sed equivalents;
//   - `oem lock` (flash_all_lock.sh): locking with a modified ROM can leave the device
//     unbootable, so no lock variant is generated.

export interface FlashStep {
  op: 'flash' | 'erase' | 'set_active' | 'reboot'
  args: string[]
}

/** Parse the fastboot steps of a stock Xiaomi flash_all*.sh. */
export function parseStockScript(text: string): FlashStep[] {
  const steps: FlashStep[] = []
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim()
    if (line.startsWith('#')) continue
    const m = line.match(/^fastboot\s+\$\*\s+(flash|erase|set_active|reboot)\b\s*(.*)$/)
    if (!m) continue
    const op = m[1] as FlashStep['op']
    // Paths are written `dirname $0`/images/x or $(dirname $0)/images/x; both contain a space,
    // so drop the prefix before splitting into arguments.
    const args = m[2]
      .replace(/`dirname \$0`\//g, '')
      .replace(/\$\(dirname \$0\)\//g, '')
      .split(/\s+/)
      .filter(Boolean)
    if (op === 'flash' && /crclist/.test(args[0] ?? '')) continue
    steps.push({ op, args })
  }
  return steps
}

/** Image files a step list needs, relative to the package root. */
export function referencedFiles(steps: FlashStep[]): string[] {
  return steps.filter((s) => s.op === 'flash').map((s) => s.args[1])
}

const q = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`

export function renderScript(opts: {
  device: string
  antiVersionFile: boolean
  wipesData: boolean
  steps: FlashStep[]
  generator: string
  /** Bundled fastboot relative to the script, used when present. */
  bundled?: string
  /** Replaces the default warning line. */
  message?: string
}): string {
  const lines: string[] = []
  const say = (s: string): void => {
    lines.push(`echo ${q(s)}`)
  }
  lines.push('#!/bin/sh')
  lines.push(`# Generated by ${opts.generator}. HyperKitchen never runs this script; you do.`)
  lines.push(
    '# Requires an UNLOCKED bootloader. Usage: ./script.sh [fastboot options, e.g. -s SERIAL]'
  )
  lines.push('# Set FASTBOOT=/path/to/fastboot to use a specific binary.')
  lines.push('set -u')
  lines.push('cd "$(dirname "$0")" || exit 1')
  if (opts.bundled) {
    lines.push(`FB="\${FASTBOOT:-}"`)
    lines.push(`if [ -z "$FB" ]; then`)
    lines.push(
      `  if [ -f ${q(opts.bundled)} ]; then FB=${q(opts.bundled)}; chmod +x "$FB" 2>/dev/null; else FB=fastboot; fi`
    )
    if (opts.bundled.includes('macos')) {
      // A zip downloaded with a browser marks the bundled binary as quarantined and macOS kills
      // it on launch; clear that attribute on this one file (xattr -d <name> <file>).
      lines.push(
        `  [ "$FB" = ${q(opts.bundled)} ] && xattr -d com.apple.quarantine "$FB" 2>/dev/null`
      )
    }
    lines.push('fi')
  } else {
    lines.push('FB="${FASTBOOT:-fastboot}"')
  }
  lines.push('OPTS="$*"')
  lines.push('die() { echo "ERROR: $*" >&2; exit 1; }')
  lines.push('# Run one fastboot command and stop at the first failure.')
  lines.push('run() { echo ">> fastboot $*"; $FB $OPTS "$@" || die "fastboot $* failed"; }')
  lines.push('getvar() { $FB $OPTS getvar "$1" 2>&1 | sed -n "s/^$1: *//p" | head -n 1; }')
  lines.push('')
  lines.push('command -v "$FB" >/dev/null 2>&1 || die "fastboot not found (set FASTBOOT=...)"')
  lines.push('echo "Waiting for the device in fastboot mode..."')
  lines.push('product=$(getvar product)')
  lines.push(
    `[ "$product" = ${q(opts.device)} ] || die "this package is for ${opts.device}, the device says '$product'"`
  )
  lines.push('unlocked=$(getvar unlocked)')
  lines.push(
    '[ "$unlocked" = "yes" ] || die "the bootloader is not unlocked; this modified ROM only boots unlocked"'
  )
  if (opts.antiVersionFile) {
    lines.push('pkg_anti=$(cat images/anti_version.txt 2>/dev/null)')
    lines.push('dev_anti=$(getvar anti | sed -n "s/^\\([0-9][0-9]*\\).*/\\1/p")')
    lines.push(
      '[ "${dev_anti:-0}" -le "${pkg_anti:-0}" ] || die "device anti-rollback version $dev_anti is greater than this package ($pkg_anti)"'
    )
  }
  lines.push('')
  say(
    opts.message ??
      (opts.wipesData
        ? 'This WIPES user data (apps, settings and internal storage) and flashes every partition.'
        : 'This keeps user data and flashes every partition.')
  )
  lines.push('printf "Type yes to continue: "')
  lines.push('read -r answer')
  lines.push('[ "$answer" = "yes" ] || die "aborted"')
  lines.push('')
  for (const s of opts.steps) lines.push(`run ${s.op} ${s.args.map(q).join(' ')}`.trimEnd())
  lines.push('echo "Done."')
  return lines.join('\n') + '\n'
}

/**
 * Windows batch version of renderScript, following the structure of the xiaomi.eu scripts
 * (cd %~dp0, bundled bin\windows\fastboot.exe, for /f + findstr to read getvar output).
 * Not run on a Windows host during development.
 */
export function renderBatch(opts: {
  device: string
  antiVersionFile: boolean
  steps: FlashStep[]
  generator: string
  message: string
}): string {
  const l: string[] = []
  const fail = (msg: string): string => `echo ERROR: ${msg} & pause & exit /B 1`
  l.push('@echo off')
  l.push(`rem Generated by ${opts.generator}. HyperKitchen never runs this script; you do.`)
  l.push('rem Requires an UNLOCKED bootloader.')
  l.push('setlocal EnableDelayedExpansion')
  l.push('cd /d "%~dp0"')
  l.push('set fastboot=bin\\windows\\fastboot.exe')
  l.push(`if not exist %fastboot% ${fail('%fastboot% not found.')}`)
  l.push('echo Waiting for the device in fastboot mode...')
  l.push('set product=')
  l.push(
    'for /f "tokens=2" %%A in (\'%fastboot% getvar product 2^>^&1 ^| findstr "\\<product:"\') do set product=%%A'
  )
  l.push(
    `if not "!product!"=="${opts.device}" ${fail(`this package is for ${opts.device}, the device says !product!`)}`
  )
  l.push('set unlocked=')
  l.push(
    'for /f "tokens=2" %%A in (\'%fastboot% getvar unlocked 2^>^&1 ^| findstr "\\<unlocked:"\') do set unlocked=%%A'
  )
  l.push(
    `if not "!unlocked!"=="yes" ${fail('the bootloader is not unlocked; this modified ROM only boots unlocked')}`
  )
  if (opts.antiVersionFile) {
    l.push('set pkg_anti=0')
    l.push('if exist images\\anti_version.txt set /p pkg_anti=<images\\anti_version.txt')
    l.push('set dev_anti=0')
    l.push(
      'for /f "tokens=2" %%A in (\'%fastboot% getvar anti 2^>^&1 ^| findstr "\\<anti:"\') do set dev_anti=%%A'
    )
    l.push(
      `if !dev_anti! GTR !pkg_anti! ${fail('device anti-rollback version is greater than this package')}`
    )
  }
  l.push(`echo ${opts.message}`)
  l.push('set /p answer=Type yes to continue: ')
  l.push('if /i not "!answer!"=="yes" exit /B 1')
  for (const s of opts.steps) {
    const args = s.args.map((a) => a.replace(/\//g, '\\')).join(' ')
    l.push(
      `%fastboot% ${s.op} ${args}`.trimEnd() + ` || (${fail(`fastboot ${s.op} ${args} failed`)})`
    )
  }
  l.push('echo Done.')
  return l.join('\r\n') + '\r\n'
}
